# Generated by Django 4.2.6 on 2023-10-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        ('authentication', '0002_userprofile_owned_books_alter_userprofile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracked_books',
            field=models.ManyToManyField(related_name='tracked_books', to='tracker.booktracker'),
        ),
    ]
